name: "Проблема в сайте"
description: "Сообщить об ошибке в сайте"
labels: ["сайт", "баг"]
projects: ["Toolbox-io/1"]
assignees:
  - denis0001-dev
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        _Спасибо, что помогаете Toolbox.io стать лучше!_
  - type: textarea
    id: desc
    attributes:
      label: "Описание"
      description: "Подробное и конкретное описание проблемы"
      placeholder: "Когда я открываю '...', происходит ..."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Что Вы ожидали?"
      description: "Подробное и конкретное описание того, что вы ожидали"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Воспроизведение"
      description: "Шаги для воспроизведения проблемы"
      placeholder: |
        1. Открыть сайт
        2. Перейти в ...
        3. Нажать ...
        4. Ошибка
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "Операционная система"
      description: "Какая у вас операционная система?"
      placeholder: "Android 11"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: "Бренд и модель устройства"
      description: "Какое у вас устройство?"
      placeholder: "Blackview A95"
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: "Ваш браузер"
      description: "Какой у вас браузер?"
      placeholder: "Chrome 122"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Скриншоты"
      description: "Приложите скриншоты, если возможно."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Правила сообщества"
      description: |
        Вы принимаете [правила сообщества](https://github.com/Toolbox-io/Toolbox-io/)?
      options:
        - label: "Я принимаю правила сообщества"
          required: true
