name: "Предложение для приложения"
description: "Предложить идею или новую функцию для приложения"
labels: ["приложение", "улучшение"]
projects: ["Toolbox-io/1"]
assignees:
  - denis0001-dev
body:
  - type: markdown
    attributes:
      value: |
        _Спасибо, что помогаете Toolbox.io стать лучше!_
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
        - label: test
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "Ваше предложение связано с проблемой?"
      description: "Если да, то пожалуйста опишите проблему."
      placeholder: "Меня очень раздражает, когда ..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: "Решение"
      description: "Что Вы хотите предложить?"
      placeholder: "Сделать так, чтобы ..."
    validations:
      required: true
